### ISSUE TITLE
Mitmproxy not working

### ISSUE THREAD

**Issue by RowanG1Bilue** [hulu/roku-dev-cli#18]
I have run the cli, deployed an app, and have opened the mitmweb. It says "connected", but I don't see any traffic, and the channel can't successfully make network requests. I get this error:

```
127.0.0.1:60659: Transparent mode failure: RuntimeError('Insufficient privileges to access pfctl. See https://mitmproxy.org/docs/latest/howto-transparent/#macos for details.')
127.0.0.1:60660: Transparent mode failure: RuntimeError('Insufficient privileges to access pfctl. See https://mitmproxy.org/docs/latest/howto-transparent/#macos for details.')
127.0.0.1:60659: mitmproxy has crashed!
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/server.py", line 279, in server_event
    for command in layer_commands:
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 257, in handle_event
    yield from super().handle_event(event)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 129, in handle_event
    yield from self.__continue(event)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 220, in __continue
    yield from self.__process(command_generator, event.reply)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 183, in __process
    command = command_generator.send(send)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 271, in _handle_event
    yield from self._ask()
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 285, in _ask
    yield from self.layer.handle_event(e)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 740, in _handle_event
    yield from self.event_to_child(handler, event)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 761, in event_to_child
    yield from self.event_to_child(stream, command.event)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 749, in event_to_child
    for command in child.handle_event(event):
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, in handle_event
    command = command_generator.send(send)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 136, in _handle_event
    yield from self.client_state(event)
  File "/usr/local/Cellar/mitmproxy/7.0.2/libexec/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line 162, in state_wait_for_request_headers
    assert self.conte
```xt.server.address
AssertionError

**Comment by strattonbrazil** [comment]
Hi @RowanG1Bilue , that looks like a permissions error. Have you followed the linked steps in the error message? 

https://mitmproxy.org/docs/latest/howto-transparent/#macos

**Comment by RowanG1Bilue** [comment]
I think the main issue is that I was trying to connect the Roku and PC via Wi-Fi, but I see now that you need a ethernet connection with a 10/100 speed adapter.
